easy_admin:
  site_name: 'Arijeet Baruah''s <em style="font-size: 80%;">Blog</em>'
  user:
    display_name: true
    display_avatar: false
    name_property_path: 'Username'
  design:
    menu:
      - 'Skills'
      - 'Experience'
      - label: 'Clients'
      - 'Projects'
      - 'ProjectCodeSnippets'
    form_theme:
      - '@EasyAdmin/form/bootstrap_4.html.twig'
    brand_color: 'red'
  entities:
    # List the entity class name you want to manage
    Skills:
      class: App\Entity\Skills
    Projects:
      class: App\Entity\Projects
      form:
        fields:
          - title
          - { property: 'body', type: 'fos_ckeditor' }
          - { property: 'start_date', type_options: { widget: 'single_text' } }
          - { property: 'end_date', type_options: { widget: 'single_text' } }
          - skills
          - code_snippet_id
    Experience:
      class: App\Entity\Experience
      form:
        fields:
          - title
          - { property: 'body', type: 'fos_ckeditor' }
          - { property: 'start_date', type_options: { widget: 'single_text' } }
          - { property: 'end_date', type_options: { widget: 'single_text' } }
    ProjectCodeSnippets:
      class: App\Entity\ProjectCodeSnippets
      form:
        fields:
          - project
          - name
          - code
