Certificate:
  type: object
  config:
    description: "Certificate"
    fields:
      id:
        type: "Int"
      title:
        type: "String"
      body:
        type: "String"
      start_date:
        type: "DateTime"
      end_date:
        type: "DateTime"
