Project:
  type: object
  config:
    description: "Project"
    fields:
      id:
        type: "Int"
      title:
        type: "String"
      body:
        type: "String"
      start_date:
        type: "DateTime"
      end_date:
        type: "DateTime"
      skills:
        type: "[Skill]"
      code_snippet_id:
        type: "[ProjectCodeSnippets]"
