Query:
  type: object
  config:
    description: "Apartments ORM repository"
    fields:
      User:
        type: "User"
        args:
          id:
            description: "Resolves using the user id."
            type: "Int"
        resolve: "@=resolver('User', [args])"
      Users:
        type: "[User]"
        resolve: "@=resolver('Users', [args])"
      Skill:
        type: "Skill"
        args:
          id:
            description: "Resolves using the skill id."
            type: "Int"
          title:
            description: "Resolves using the skill title."
            type: "String"
        resolve: "@=resolver('Skill', [args])"
      Skills:
        type: "[Skill]"
        resolve: "@=resolver('Skills', [args])"
      Projects:
        type: "[Project]"
        resolve: "@=resolver('Projects', [args])"
      Project:
        type: "Project"
        args:
          id:
            description: "Resolves using the project id."
            type: "Int"
          title:
            description: "Resolves using the project title."
            type: "String"
        resolve: "@=resolver('Project', [args])"
      Experiences:
        type: "[Experience]"
        resolve: "@=resolver('Experiences', [args])"
      Experience:
        type: "Experience"
        args:
          id:
            description: "Resolves using the project id."
            type: "Int"
          title:
            description: "Resolves using the project title."
            type: "String"
        resolve: "@=resolver('Experience', [args])"
      Certificates:
        type: "[Certificate]"
        resolve: "@=resolver('Certificates', [args])"
      Certificate:
        type: "Certificate"
        args:
          id:
            description: "Resolves using the project id."
            type: "Int"
          title:
            description: "Resolves using the project title."
            type: "String"
        resolve: "@=resolver('Certificate', [args])"
      Educations:
        type: "[Educations]"
        resolve: "@=resolver('Educations', [args])"
      Education:
        type: "Educations"
        args:
          id:
            description: "Resolves using the Education id."
            type: "Int"
          title:
            description: "Resolves using the Education title."
            type: "String"
        resolve: "@=resolver('Education', [args])"
